app:
  name: "go-blog"
  port: 3000
  environment: "local"
  url: "http://localhost:3000/api/v1"
postgres:
  connstr: "postgres://postgres:example@db:5432/postgres?sslmode=disable"
logger:
  encoding: json
